services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TYPO3\CMS\Recordlist\:
    resource: '../Classes/*'
  TYPO3\CMS\Recordlist\Controller\RecordListController:
    tags: ['backend.controller']
  TYPO3\CMS\Recordlist\HookProvider\AddToRecordListHookProvider:
    tags:
      - name: event.listener
        identifier: 'record-list-content-legacy-hook'
        event: TYPO3\CMS\Recordlist\Event\RenderAdditionalContentToRecordListEvent